apiVersion: v1
kind: Service
metadata:
  name: jenkins-http
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 25000
      protocol: TCP
      targetPort: 8080
  selector:
    app: jenkins
  clusterIP: 10.100.100.254
  externalIPs:
  - 192.168.49.3
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 25001
      protocol: TCP
      targetPort: 50000
  selector:
    app: jenkins
  clusterIP: 10.100.100.255
  externalIPs:
  - 192.168.49.3

